{% set name = "rubin-env" %}
{% set version = "8.0.0" %}
{% set build_number = 17 %}

package:
  name: {{ name }}
  version: {{ version }}

build:
  skip: True  # [python_impl == 'pypy' or win or py != 311]
  number: {{ build_number }}

outputs:
  - name: rubin-env-nosysroot
    script: build-nosysroot.sh
    # Since all requirements are required "at run time" for the
    # Rubin developers, all requirements are fundamentally
    # run requirements. However, we've attempted to organize
    # requirements as build-like, host-like, or run-like, in
    # order inform any evolution of this recipe.
    requirements:
      host:
        - python
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        - {{ compiler('fortran') }}
        - apr
        - cfitsio
        - curl
        - fftw
        - gsl
        - libaprutil
        - libblas
        - libcblas
        - liblapack
        - liblapacke
        - log4cxx
        - minuit2
        - numpy
        - openblas
        - starlink-ast
        - wcslib
        - xpa
      run_constrained:
        - impi_rt == 9999999999999
      run:
        # jq is special - it is needed for the pin-it utility in this package
        - jq
        ###################################################
        # build-like dependencies
        # As part of our scons build process, we do run tests, so
        # these really are required to perform a build.
        # Note that "testing" in conda-forge should be limited to testing
        # successful packaging, and not testing code.
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        - {{ compiler('fortran') }}
        # The above are needed to get the official conda-forge versions.
        # The below is needed to get convenience symlinks for users to invoke.
        - compilers
        - cmake
        - coverage >=3.6,!=6.3,!=7.0.0
        - coveralls
        - doxygen
        - flake8 =6.0
        - libboost-python-devel
        - libblas * *openblas
        - openblas
        - make
        - meson
        - nose
        - pep8-naming
        - pkg-config >=0.29.2
        - pip
        - psutil
        - pytest <8.1.0
        - pytest-cov
        - pytest-doctestplus
        - pytest-openfiles
        - pytest-runner
        - pytest-session2file
        - pytest-subtests
        - pytest-vcr
        - pytest-xdist
        - setuptools <72
        - scons

        ###################################################
        # host-like and run-like
        # These are mostly run-like, but for the same reasons as
        # above, we need most of these at build time, so they are mostly
        # host-like
        - apr {{ apr }}.*
        - cffi {{ cffi }}.*
        - cfitsio {{ cfitsio }}.*
        - eigen {{ eigen }}.*
        - eups
        - firefly-client
        - gsl {{ gsl }}.*
        - libaprutil {{ libaprutil }}.*
        - libboost-python-devel {{ libboost_python_devel }}.*
        - libcxx {{ libcxx }}.*  # [not aarch64]
        - llvmlite
        - log4cxx {{ log4cxx }}.*
        - minuit2 {{ minuit2 }}.*
        - ndarray {{ ndarray }}.*
        - ndarray >=1.6.4
        - numba
        - numpy {{ numpy }}.*
        - starlink-ast {{ starlink_ast }}.*
        - wcslib {{ wcslib }}.*
        - xpa {{ xpa }}.*
        - yaml-cpp {{ yaml_cpp }}.*

        ###################################################
        # run-like
        - alembic
        - astropy >=5.3
        - astroquery <0.4.8
        - autograd
        - backoff
        - boto3 !=1.33.0
        - bottleneck
        - cassandra-driver  # [linux64]
        - click !=8.1.0,!=8.1.1
        - coloredlogs
        # conda is required for runtime inspection of installed software
        - conda
        - configparser
        - defusedxml
        - deprecated
        - dustmaps
        - emcee
        - esutil !=0.6.15
        - fastavro
        - fitsio
        - fitsverify
        - frozendict >=2.2.0
        - future
        - galsim
        - getcalspec >=2.0.0
        - git !=2.45.1
        - git-lfs
        - h5py
        - healpy
        - healsparse
        - hpgeom >=0.8.2
        - htcondor >=23.0,<23.1
        - humanize
        - idds-client >=0.11.0
        - idds-doma >=0.11.0
        - iminuit >=2
        - lmfit <1.3
        - lsstdesc.coord
        - lsst-ts-xml
        - matplotlib-base >=3.8.0,<3.9
        - moto >=3,<5
        - mpi4py
        - nest-asyncio
        - networkx
        - ngmix-core
        - numexpr =2
        - {{ pin_compatible('numpy') }}
        - panda-client !=1.5.65
        - pandas =2
        - parsl ==2023.06.12
        - pgcli
        - photutils >=1.7
        - piff ==1.3.3
        - prmon  # [linux]
        - psycopg2 =2
        - pyarrow
        - pybind11 <2.11
        - pydantic >=2,<3
        - pyld
        - pysynphot
        - pytables
        - python
        - pytorch
        - pyyaml
        - requests
        - ruff ==0.1.7
        - schwimmbad
        - scikit-image !=0.18
        - scikit-learn
        - scipy >=1.10,<1.12.0
        - seaborn
        - skyproj >=1.1.0,<2
        - spherematch
        - sqlalchemy
        - sqlite
        - threadpoolctl
        - torchvision
        - tqdm
        - treecorr =4
        - ws4py

    test:
      commands:
        # grep pin-it output for python dependency
        - pin-it rubin-env-nosysroot | grep "python="
        # ensure binary compatibility; bump major version if not
        - '[ $(echo __GXX_ABI_VERSION | ${CXX} -E - | tail -1) == 1017 ]'  # [linux]
        - '[ $(echo __GXX_ABI_VERSION | ${CXX} -E - | tail -1) == 1002 ]'  # [osx]

  - name: rubin-env
    requirements:
      host:
        - python
      run:
        - {{ pin_subpackage("rubin-env-nosysroot", exact=True) }}
        - sysroot_linux-64 =2.17  # [linux64]
        - python
    test:
      commands:
        # grep pin-it output for python dependency
        - pin-it rubin-env | grep "python="
        # ensure binary compatibility; bump major version if not
        - '[ $(echo __GXX_ABI_VERSION | ${CXX} -E - | tail -1) == 1017 ]'  # [linux]
        - '[ $(echo __GXX_ABI_VERSION | ${CXX} -E - | tail -1) == 1002 ]'  # [osx]

  - name: rubin-env-rsp
    requirements:
      host:
        - python
      run:
        - {{ pin_subpackage("rubin-env", exact=True) }}
        # All are from sciplat-lab unless otherwise stated
        - astroplan # sims
        - astrowidgets >=0.3
        - awkward
        - awkward-pandas
        - black
        - bokeh
        - bqplot
        - ciso8601
        - cloudpickle
        - cookiecutter
        - dash >=2.11
        - dask-core
        - datashader
        - fastparquet
        - ffmpeg # RFC-846
        - freetype-py
        - gcsfs
        - geoviews
        - gh
        - ginga >=3
        - graphviz
        - hatch-jupyter-builder
        - hatch-nodejs-version
        - hatchling
        - hdf5plugin
        - holoviews
        - httpx # RFC-969
        - hvplot
        - imagemagick # RFC-846
        - intake
        - intake-parquet
        - ipyevents
        - ipykernel
        - ipympl
        - ipyvolume
        - ipywidgets
        - isort !=5.11.0
        - jedi
        - jupyter
        - jupyter-packaging
        - jupyter-resource-usage
        - jupyter-server-proxy
        - jupyter_bokeh
        - jupyterhub
        - jupyterlab >=4,<5
        - jupyterlab_execute_time
        - jupyterlab_iframe
        - jupyterlab_widgets
        - jupyterlab-variableinspector
        - lsst-efd-client
        - mypy
        - mysqlclient
        - nb_black
        - nbconvert-webpdf
        - nbdime
        - nbval
        - nodejs >=16
        - panel >=0.12.1 # shared
        - papermill
        - paramnb
        - partd
        - pep8 # shared
        - plotly
        - pre-commit
        - pyflakes # shared
        - pypandoc
        - pyshp
        - python-snappy
        - python-socketio
        - pythreejs
        - pyviz_comms
        - pyvo
        - regions
        - ripgrep
        - rubin-scheduler
        - rubin-sim
        - sbpy  # [not aarch64]
        - schedview
        - sidecar
        - snappy
        - terminado
        - toolz
        - wget
        - xarray
        - yarn
    test:
      commands:
        # grep pin-it output for yarn dependency
        - pin-it rubin-env-rsp | grep "yarn="

  - name: rubin-env-developer
    requirements:
      host:
        - python
      run:
        - {{ pin_subpackage("rubin-env", exact=True) }}
        - astrowidgets >=0.3
        - black
        - bokeh
        - dask-jobqueue
        - datashader
        - fastparquet
        - ffmpeg
        - holoviews
        - hvplot
        - imagemagick
        - ipdb
        - ipympl
        - ipython
        - isort !=5.11.0
        - jedi
        - jupyter
        - jupyterlab >=4,<5
        - jupyterlab_server
        - line_profiler
        - lsst-documenteer-pipelines
        - lsst-documenteer-technote
        - lsst-efd-client
        - mypy
        - mysqlclient
        - panel >=0.12.1
        - pep8
        - postgresql
        - pre-commit
        - pyct
        - pydocstyle
        - pyflakes
        - pytest-profiling
        - python-build
        - pyvo
        - ripgrep
        - snakeviz
        - types-deprecated
        - types-pkg_resources
        - types-python-dateutil
        - types-pyyaml
        - types-requests
        - types-setuptools
        - types-urllib3
    test:
      commands:
        # grep pin-it output for black dependency
        - pin-it rubin-env-developer | grep "black"

  - name: rubin-env-extras
    requirements:
      host:
        - python
      run:
        - {{ pin_subpackage("rubin-env", exact=True) }}
        - {{ pin_subpackage("rubin-env-rsp", exact=True) }}
        - {{ pin_subpackage("rubin-env-developer", exact=True) }}
        - rubin-sim >=0.12.0
    test:
      commands:
        # grep pin-it output for rubin-env-developer dependency
        # Can't do rubin-sim due to lack of ARM
        - pin-it rubin-env-extras | grep "rubin-env-developer"

about:
  home: https://github.com/conda-forge/rubinenv-feedstock
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: Metapackage to install the Rubin Observatory's common software environment.

  description: |
    This metapackage exists to define the Rubin Observatory common software
    environment, including version specifications where needed, while allowing
    users flexibility when installing additional packages into the same environment.

extra:
  recipe-maintainers:
    - mwittgen
    - timj
    - ktlim
    - erykoff
    - beckermr
