{% set name = "rubin-env" %}
{% set version = "10.0.0" %}
{% set build_number = 3 %}

package:
  name: {{ name }}
  version: {{ version }}

build:
  skip: True  # [python_impl == 'pypy' or win or py != 312]
  number: {{ build_number }}

outputs:
  - name: rubin-env-nosysroot
    script: build-nosysroot.sh
    # Since all requirements are required "at run time" for the
    # Rubin developers, all requirements are fundamentally
    # run requirements. However, we've attempted to organize
    # requirements as build-like, host-like, or run-like, in
    # order inform any evolution of this recipe.
    requirements:
      host:
        - python
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        - {{ compiler('fortran') }}
        - apr
        - cfitsio
        - curl
        - fftw
        - gsl
        - libaprutil
        - libblas
        - libcblas
        - liblapack
        - liblapacke
        - log4cxx
        - minuit2
        - numpy
        - openblas
        - starlink-ast
        - wcslib
        - xpa
      run_constrained:
        - impi_rt == 9999999999999
      run:
        # jq is special - it is needed for the pin-it utility in this package
        - jq >=1.7.1
        ###################################################
        # build-like dependencies
        # As part of our scons build process, we do run tests, so
        # these really are required to perform a build.
        # Note that "testing" in conda-forge should be limited to testing
        # successful packaging, and not testing code.
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        - {{ compiler('fortran') }}
        # The above are needed to get the official conda-forge versions.
        # The below is needed to get convenience symlinks for users to invoke.
        - compilers >=1.9.0
        - cmake >=3.31.5
        - coverage >=7.6.12
        - coveralls >=4.0.1
        - doxygen >=1.13.2
        - eups >=2.2.10
        - flake8 ==7.1.1
        - libblas * *openblas
        - openblas
        - make >=4.4.1
        - meson >=1.7.0
        - pep8-naming >=0.14.1
        - pip >=25.0.1
        - pkg-config >=0.29.2
        - psutil >=5.9.8
        - pytest >=8.3.4
        - pytest-cov >=6.0.0
        - pytest-doctestplus >=1.4.0
        - pytest-runner >=6.0.0
        - pytest-session2file >=0.1.11
        - pytest-subtests >=0.14.1
        - pytest-vcr >=1.0.2
        - pytest-xdist >=3.6.1
        - setuptools >=75.8.0
        - scons >=4.8.1

        ###################################################
        # host-like and run-like
        # These are mostly run-like, but for the same reasons as
        # above, we need most of these at build time, so they are mostly
        # host-like
        - apr {{ apr }}.*
        - cffi {{ cffi }}.*
        - cfitsio {{ cfitsio }}.*
        - eigen {{ eigen }}.*
        - gsl {{ gsl }}.*
        - libaprutil {{ libaprutil }}.*
        - libboost-python-devel {{ libboost_python_devel }}.*
        - libcxx {{ libcxx }}.*  # [not aarch64]
        - llvmlite
        - log4cxx {{ log4cxx }}.*
        - minuit2 {{ minuit2 }}.*
        - ndarray {{ ndarray }}.*
        - ndarray >=1.6.4
        - numba
        - numpy {{ numpy }}.*
        - starlink-ast {{ starlink_ast }}.*
        - wcslib {{ wcslib }}.*
        - xpa {{ xpa }}.*
        - yaml-cpp {{ yaml_cpp }}.*

        ###################################################
        # run-like
        - alembic >=1.14.1
        - astropy-base >=7.0.1, <8
        - astroplan >=0.10.1
        - astroquery ==0.4.9
        - autograd >=1.7.0
        - backoff >=2.2.1
        - batoid >=0.7.3
        - batoid-rubin >=0.5.0
        - boto3 >=1.36.3
        - bottleneck >=1.4.2
        - cassandra-driver >=3.28.0  # [linux64]
        - click >=8.1.7
        - coloredlogs >=15.0.1
        - colour-science >=0.4.6
        - configparser >=7.1.0
        - danish >=0.5.0
        - deepdiff >=8.2.0
        - defusedxml >=0.7.1
        - deprecated >=1.2.18
        - dustmaps >=1.0.13
        - emcee >=3.1.6
        - esutil >=0.6.11,!=0.6.15
        - fastavro >=1.10.0
        - firefly-client >=3.2.0
        - fitsio >=1.2.5
        - fitsverify >=4.22
        - frozendict >=2.4.6
        - fsspec >=2025.2.0
        - future >=1.0.0
        - gaiaxpy >=2.1.2
        - galsim >=2.6.3
        - getcalspec >=2.1.0
        - git >=2.47.1
        - git-lfs >=3.6.1
        - h5py >=3.12.1
        - healpy >=1.18.0
        - healsparse >=1.10.0
        - hpgeom >=1.4.0
        - htcondor >=24.0,<24.1
        - humanize >=4.11.0
        - idds-client >=2.1.37
        - idds-doma >=2.1.37
        - iminuit >=2.30.0
        - jax >=0.4.35
        - lmfit >=1.3,<1.4
        - lsstdesc.coord >=1.3.0
        - lsst-ts-xml >=22.1.0
        - matplotlib-base >=3.10
        - maturin >=1.8.2
        - moto >=5.0.28
        - mpi4py >=4.0.2
        - nest-asyncio >=1.6.0
        - networkx >=3.4.2
        - ngmix-core >=2.3.2
        - numexpr >=2.10.2,<3
        - numpy
        - opencv >=4.10.0
        - packaging >=24.2
        - panda-client >=1.5.82
        - pandas >=2.2.3,<3
        - paramiko >=3.4.0
        - parsl ==2024.12.23
        - patch >=2.7.6
        - pgcli >=4.1.0
        - photutils >=2.1.0
        - piff >=1.5
        - prmon >=3.1.1  # [linux]
        - psycopg2 >=2.9.9,<3
        - pyarrow >=19.0.0
        - pybind11 >=2.13.6
        - pydantic >=2.10.1,<3
        - pyld >=2.0.4
        - pytables >=3.10.2
        - python >=3.12,<3.13
        - python-confluent-kafka >=2
        - pytorch >=2.5.1
        - pyyaml >=6.0.2
        - pz-rail-base >=1.0.8
        - pz-rail-sklearn >=1.0.2
        - qp >=0.9.3
        - requests >=2.32.3
        - rucio-clients >=36.3.0
        - ruff ==0.9.6
        - s3fs >=2025.2.0
        - schwimmbad >=0.4.2
        - scikit-image >=0.25.0
        - scikit-learn >=1.6.1
        - scipy >=1.13.0,<1.14
        - seaborn >=0.13.2
        - skyproj >=2.0.0
        - sorcha >=0.9.2
        - spherematch >=0.10.1
        - sqlalchemy >=2.0.23
        - sqlite >=3.48.0
        - threadpoolctl >=3.5.0
        - torchvision >=0.20.1
        - tqdm >=4.67.1
        - treecorr >=5,<6
        - webdav4 >=0.10.0
        - ws4py >=0.5.1

    test:
      commands:
        # grep pin-it output for python dependency
        - pin-it rubin-env-nosysroot | grep "python="
        # ensure binary compatibility; bump major version if not
        - '[ $(echo __GXX_ABI_VERSION | ${CXX} -E - | tail -1) == 1018 ]'  # [linux]
        - '[ $(echo __GXX_ABI_VERSION | ${CXX} -E - | tail -1) == 1002 ]'  # [osx]

  - name: rubin-env
    requirements:
      host:
        - python
      run:
        - {{ pin_subpackage("rubin-env-nosysroot", exact=True) }}
        - {{ stdlib("c") }}
        - python
    test:
      commands:
        # grep pin-it output for python dependency
        - pin-it rubin-env | grep "python="
        # ensure binary compatibility; bump major version if not
        - '[ $(echo __GXX_ABI_VERSION | ${CXX} -E - | tail -1) == 1017 ]'  # [linux]
        - '[ $(echo __GXX_ABI_VERSION | ${CXX} -E - | tail -1) == 1002 ]'  # [osx]

  - name: rubin-env-rsp
    requirements:
      host:
        - python
      run:
        - {{ pin_subpackage("rubin-env", exact=True) }}
        # All are from sciplat-lab unless otherwise stated
        - astrowidgets >=0.3.0
        - awkward >=2.6.4
        - awkward-pandas >=2023.8.0
        - black ==25.1
        - black-jupyter
        - bokeh >=3.3.2
        - bqplot >=0.12.43
        - ciso8601 >=2.3.1
        - cloudpickle >=3.0.0
        - cookiecutter >=2.6.0
        - dask-core >=2025.1.0
        - datashader >=0.17.0
        - fastparquet >=2024.2.0
        - ffmpeg >=4.4.0
        - freetype-py >=2.4.0
        - gcsfs >=2024.3.1
        - geoviews >=1.12.0
        - gh >=2.46.0  # 2.49.0 is not available on aarch64
        - ginga >=5.0.1
        - graphviz >=9.0.0
        - hatch-jupyter-builder >=0.9.1
        - hatch-nodejs-version >=0.3.2
        - hatchling >=1.24.2
        - hdf5plugin >=4.4.0
        - holoviews >=1.18.3
        - httpx >=0.27.0
        - hvplot >=0.9.0
        - imagemagick >=7.1.1_21
        - intake >=2.0.5
        - intake-parquet >=0.3.0
        - ipyevents >=2.0.2
        - ipykernel >=6.29.3
        - ipympl >=0.9.4
        - ipyvolume >=0.6.3
        - ipywidgets >=8.1.2
        - isort >=6
        - jedi >=0.19.1
        - jupyter >=1.0.0
        - jupyter-packaging >=0.12.3
        - jupyter-resource-usage >=1.0.2
        - jupyter-server-proxy >=4.1.2
        - jupyter_bokeh >=4.0.4
        - jupyterhub >=4.1.5
        - jupyterlab >=4.1.8,<5
        - jupyterlab-variableinspector >=3.2.1
        - jupyterlab_execute_time >=3.1.2
        - jupyterlab_iframe >=0.5.0
        - jupyterlab_widgets >=3.0.10
        - lsst-efd-client >=0.12.0
        - mermaid-py >=0.7.0
        - mypy >=1.7.1
        - mysqlclient >=2.2.1
        - nbconvert-webpdf >=7.7.1
        - nbdime >=4.0.1
        - nbval >=0.11.0
        - nodejs >=20.12.2
        - panel >=1.4.2
        - papermill >=2.6.0
        - paramnb >=2.0.4
        - partd >=1.4.1
        - pep8 >=1.7.1
        - plotly >=5.22.0
        - pre-commit >=3.6.0
        - pyflakes >=3.0.1
        - pypandoc >=1.13
        - pyshp >=2.3.1
        - python-snappy >=0.7.1
        - python-socketio >=5.11.2
        - pythreejs >=2.4.2
        - pyviz_comms >=3.0.1
        - pyvo >=1.5
        - regions >=0.9
        - ripgrep >=14.0.3
        - rubin-scheduler >=1.1.1
        - rubin-sim >=2.0.0
        - sbpy >=0.3.0
        - schedview >=0.11.1
        - sidecar >=0.7.0
        - snappy >=1.1.10
        - terminado >=0.18.1
        - toolz >=0.12.1
        - wget >=1.21.4
        - xarray >=2024.3.0
        - yarn >=4.2.1
    test:
      commands:
        # grep pin-it output for yarn dependency
        - pin-it rubin-env-rsp | grep "yarn="

  - name: rubin-env-developer
    requirements:
      host:
        - python
      run:
        - {{ pin_subpackage("rubin-env", exact=True) }}
        - astrowidgets >=0.3
        - black ==25.1
        - bokeh >=3.3.2
        - clang-format >=18.0.0
        - dask-jobqueue >=0.8.5
        - datashader >=0.17.0
        - fastparquet >=2024.2.0
        - ffmpeg >=4.4.0
        - holoviews >=1.18.3
        - hvplot >=0.9.0
        - imagemagick >=7.1.1_21
        - ipdb >=0.13.13
        - ipympl >=0.9.4
        - ipython >=8.22.2
        - isort >=6
        - jedi >=0.19.1
        - jupyter >=1.0.0
        - jupyterlab >=4.1.8,<5
        - jupyterlab_server >=2.27.1
        - line_profiler >=4.1.1
        - lsst-documenteer-pipelines ==0.8.2
        - lsst-documenteer-technote ==0.8.2
        - lsst-efd-client >=0.12.0
        - mermaid-py >=0.7.0
        - mypy >=1.7.1
        - mysqlclient >=2.2.1
        - panel >=1.4.2
        - pep8 >=1.7.1
        - postgresql >=16.2
        - pre-commit >=3.6.0
        - pyct >=0.5.0
        - pydocstyle >=6.3.0
        - pyflakes >=3.0.1
        - pytest-profiling >=1.8.1
        - python-build >=1.2.1
        - pyvo >=1.5
        - ripgrep >=14.0.3
        - snakeviz >=2.2.0
        - sphinx-automodapi >=0.16.0,!=0.17.0
        - types-deprecated >=1.2.9.20240311
        - types-pkg_resources >=0.1.3
        - types-python-dateutil >=2.9.0.20240316
        - types-pyyaml >=6.0.12.20240311
        - types-requests >=2.31.0.6
        - types-setuptools >=69.5.0.20240423
        - types-urllib3 >=1.26.25.14
    test:
      commands:
        # grep pin-it output for black dependency
        - pin-it rubin-env-developer | grep "black"

  - name: rubin-env-extras
    requirements:
      host:
        - python
      run:
        - {{ pin_subpackage("rubin-env", exact=True) }}
        - {{ pin_subpackage("rubin-env-rsp", exact=True) }}
        - {{ pin_subpackage("rubin-env-developer", exact=True) }}
        - rubin-sim >=2.0.0
    test:
      commands:
        # grep pin-it output for rubin-env-developer dependency
        # Can't do rubin-sim due to lack of ARM
        - pin-it rubin-env-extras | grep "rubin-env-developer"

about:
  home: https://github.com/conda-forge/rubinenv-feedstock
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: Metapackage to install the Rubin Observatory's common software environment.

  description: |
    This metapackage exists to define the Rubin Observatory common software
    environment, including version specifications where needed, while allowing
    users flexibility when installing additional packages into the same environment.

extra:
  recipe-maintainers:
    - mwittgen
    - timj
    - ktlim
    - erykoff
    - beckermr
    - roceb
    - athornton
