{% set name = "rubin-env" %}
{% set version = "5.1.0" %}
{% set build_number = 7 %}

package:
  name: {{ name }}
  version: {{ version }}

build:
  skip: True  # [python_impl == 'pypy' or win or py != 310]
  number: {{ build_number }}

outputs:
  - name: rubin-env-nosysroot
    script: build-nosysroot.sh
    # Since all requirements are required "at run time" for the
    # Rubin developers, all requirements are fundamentally
    # run requirements. However, we've attempted to organize
    # requirements as build-like, host-like, or run-like, in
    # order inform any evolution of this recipe.
    requirements:
      host:
        - python
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        - {{ compiler('fortran') }}
        - apr
        - boost
        - cfitsio
        - curl
        - fftw
        - gsl
        - libaprutil
        - libblas
        - libcblas
        - liblapack
        - liblapacke
        - log4cxx
        - minuit2
        - mpich
        - numpy
        - xpa
        - starlink-ast
        - wcslib
      run:
        # jq is special - it is needed for the pin-it utility in this package
        - jq
        ###################################################
        # build-like dependencies
        # As part of our scons build process, we do run tests, so
        # these really are required to perform a build.
        # Note that "testing" in conda-forge should be limited to testing
        # successful packaging, and not testing code.
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        - {{ compiler('fortran') }}
        # The above are needed to get the official conda-forge versions.
        # The below is needed to get convenience symlinks for users to invoke.
        - compilers
        - cmake
        # Coverage 6.3 is breaking with NFS and multi-process testing.
        # Coverage 7.0 is breaking with + in pathnames.
        - coverage >=3.6,!=6.3,<7
        - coveralls
        - doxygen
        - flake8 =4.0
        - make
        - nose
        - pep8-naming
        - pip
        - psutil
        - pytest
        - pytest-cov
        - pytest-doctestplus
        - pytest-flake8
        - pytest-openfiles
        - pytest-runner
        - pytest-session2file
        - pytest-subtests
        - pytest-xdist
        - scons

        ###################################################
        # host-like and run-like
        # These are mostly run-like, but for the same reasons as
        # above, we need most of these at build time, so they are mostly
        # host-like
        - apr {{ apr }}.*
        - boost {{ boost }}.*
        - cffi {{ cffi }}.*
        - cfitsio {{ cfitsio }}.*
        - cython {{ cython }}.*
        - eigen {{ eigen }}.*
        - eups
        - firefly-client
        - galsim
        - gsl {{ gsl }}.*
        - libaprutil {{ libaprutil }}.*
        # there is some issue with pex_exceptions with clang 11 and libcxx 12
        # until it is tracked down, it makes sense to keep these at the same
        # major version
        - libcxx =={{ cxx_compiler_version }}.*  # [osx]
        - llvmlite
        - log4cxx {{ log4cxx }}.*
        - minuit2 {{ minuit2 }}.*
        - mpich {{ mpich }}.*
        - ndarray {{ ndarray }}.*
        - numpy {{ numpy }}.*
        - numba
        - starlink-ast {{ starlink_ast }}.*
        - wcslib {{ wcslib }}.*
        - xpa {{ xpa }}.*
        - yaml-cpp {{ yaml_cpp }}.*

        ###################################################
        # run-like
        - alembic
        - astropy
        - astroquery
        - autograd
        - backoff
        - boto3
        - bottleneck
        - cassandra-driver  # [linux64]
        # conda is required for runtime inspection of installed software
        - conda
        - configparser
        - click !=8.1.0,!=8.1.1
        - coloredlogs
        - deprecated
        - dustmaps
        - emcee
        - esutil
        - fastavro
        - future
        - getcalspec >=2.0.0
        - git
        - git-lfs
        - h5py
        - healpy
        - healsparse
        - hpgeom >=0.8.2
        - htcondor
        - humanize
        - idds-client >=0.11.0
        - idds-doma >=0.11.0
        - iminuit >=2
        - lmfit <1.0.3
        - lsstdesc.coord
        - matplotlib-base !=3.6.0,<3.7.0
        - moto >=3
        - mpi4py
        - networkx
        - numexpr =2
        - {{ pin_compatible('numpy') }}
        - pandas
        - parsl =1.2
        - pgcli
        - photutils >=0.7
        - piff
        - prmon  # [linux]
        - psycopg2 =2
        - pyarrow
        - pybind11
        - pydantic
        - pyld
        - pysynphot
        - pytables
        - python
        - pytorch
        - pyyaml
        - requests
        - schwimmbad
        - scikit-image !=0.18
        - scikit-learn
        - scipy
        - seaborn
        - skyproj
        - spherematch
        - sqlalchemy <2
        - sqlite
        - threadpoolctl
        - tqdm
        - treecorr =4
        - ws4py

    test:
      commands:
        # grep pin-it output for python dependency
        - pin-it rubin-env-nosysroot | grep "python="
        # ensure binary compatibility; bump major version if not
        - '[ $(echo __GXX_ABI_VERSION | ${CXX} -E - | tail -1) == 1014 ]'  # [linux]
        - '[ $(echo __GXX_ABI_VERSION | ${CXX} -E - | tail -1) == 1002 ]'  # [osx]

  - name: rubin-env
    requirements:
      host:
        - python
      run:
        - {{ pin_subpackage("rubin-env-nosysroot", exact=True) }}
        - sysroot_linux-64 =2.17  # [linux64]
        - python
    test:
      commands:
        # grep pin-it output for python dependency
        - pin-it rubin-env | grep "python="
        # ensure binary compatibility; bump major version if not
        - '[ $(echo __GXX_ABI_VERSION | ${CXX} -E - | tail -1) == 1014 ]'  # [linux]
        - '[ $(echo __GXX_ABI_VERSION | ${CXX} -E - | tail -1) == 1002 ]'  # [osx]

  - name: rubin-env-rsp
    requirements:
      host:
        - python
      run:
        - {{ pin_subpackage("rubin-env", exact=True) }}
        # All are from sciplat-lab unless otherwise stated
        - astroplan # sims
        - astroquery
        - astrowidgets  # [not aarch64]
        - awkward
        - awkward-numba
        - black
        - bokeh
        - bqplot
        - ciso8601  # [not aarch64]
        - cloudpickle
        - cookiecutter
        - dash
        - dask
        - dask-kubernetes
        - dask_labextension
        - datashader
        - distributed
        - fastparquet
        - ffmpeg # RFC-846
        - freetype-py
        - gcsfs
        - geoviews
        - ginga >=3,<4
        - graphviz
        - holoviews
        - hvplot
        - imagemagick # RFC-846
        - intake
        - intake-parquet
        - ipyevents
        - ipykernel
        - ipympl
        - ipyvolume
        - ipywidgets
        - isort !=5.11.0
        - jedi
        - jupyter
        - jupyter-dash  # [not aarch64]
        - jupyter-packaging
        - jupyter-server-proxy
        - jupyter_bokeh
        - jupyterhub
        - jupyterlab >=3,<4
        - jupyterlab_execute_time
        - jupyterlab_iframe
        - jupyterlab_widgets
        - jupyterlab-variableinspector
        - mamba
        - mypy
        - mysqlclient
        - nbconvert-webpdf
        - nbdime
        - nbval
        - nodejs >=16
        - numba
        - panel >=0.12.1  # shared
        - papermill
        - paramnb
        - parsl
        - partd
        - pep8 # shared
        - plotly
        - pre-commit
        - pyflakes # shared
        - pypandoc
        - pyshp
        - python-snappy
        - python-socketio
        - pythreejs
        - pyviz_comms
        - pyvo
        - sidecar
        - snappy
        - terminado
        - toolz
        - wget
        - xarray
        - yarn
    test:
      commands:
        # grep pin-it output for yarn dependency
        - pin-it rubin-env-rsp | grep "yarn="

  - name: rubin-env-developer
    requirements:
      host:
        - python
      run:
        - {{ pin_subpackage("rubin-env", exact=True) }}
        - astrowidgets  # [not aarch64]
        - black
        - bokeh
        - python-build
        - dask-jobqueue
        - datashader
        - fastparquet
        - ffmpeg
        - holoviews
        - hvplot
        - imagemagick
        - ipdb
        - ipympl
        - ipython
        - isort !=5.11.0
        - jedi
        - jupyter
        - jupyterlab >=3,<4
        - jupyterlab_server
        - line_profiler
        - lsst-documenteer-pipelines
        - lsst-documenteer-technote
        - mypy
        - mysqlclient
        - numba
        - panel >=0.12.1
        - pdbpp  # [not aarch64]
        - pep8
        - postgresql
        - pre-commit
        - psycopg2
        - pyct
        - pydocstyle
        - pyflakes
        - pyvo
        - snakeviz
        - types-click
        - types-deprecated
        - types-pkg_resources
        - types-python-dateutil
        - types-pyyaml
        - types-requests
        - types-setuptools
        - types-urllib3
    test:
      commands:
        # grep pin-it output for black dependency
        - pin-it rubin-env-developer | grep "black"

  - name: rubin-env-extras
    requirements:
      host:
        - python
      run:
        - {{ pin_subpackage("rubin-env", exact=True) }}
        - {{ pin_subpackage("rubin-env-rsp", exact=True) }}
        - {{ pin_subpackage("rubin-env-developer", exact=True) }}
        - rubin-sim >=0.12.0  # [not aarch64 and not osx-arm64]
    test:
      commands:
        # grep pin-it output for rubin-env-developer dependency
        # Can't do rubin-sim due to lack of ARM
        - pin-it rubin-env-extras | grep "rubin-env-developer"

about:
  home: https://github.com/conda-forge/rubinenv-feedstock
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: Metapackage to install the Rubin Observatory's common software environment.

  description: |
    This metapackage exists to define the Rubin Observatory common software
    environment, including version specifications where needed, while allowing
    users flexibility when installing additional packages into the same environment.

extra:
  recipe-maintainers:
    - mwittgen
    - brianv0
    - timj
    - ktlim
    - beckermr
    - erykoff
