context:
  name: "rubin-env"
  version: "4.0.5dev"
  build_number: 4
  linux_gxx_abi_version: 1014
  osx_gxx_abi_version: 1002

recipe:
  name: ${{ name }}
  version: ${{ version }}

build:
  skip: 
    - win
    - match(python, "!=3.10.*")
  number: ${{ build_number }}

outputs:
  - package:
      name: rubin-env-nosysroot
    build:
      script: build-nosysroot.sh
    # Since all requirements are required "at run time" for the
    # Rubin developers, all requirements are fundamentally
    # run requirements. However, we've attempted to organize
    # requirements as build-like, host-like, or run-like, in
    # order inform any evolution of this recipe.
    requirements:
      host:
        - python
        - ${{ compiler('c') }}
        - ${{ compiler('cxx') }}
        - ${{ compiler('fortran') }}
        - apr
        - boost
        - cfitsio
        - curl
        - fftw
        - gsl
        - libaprutil
        - libblas
        - libcblas
        - liblapack
        - liblapacke
        - log4cxx
        - minuit2
        - mpich
        - numpy ==1.21.6
        - xpa
        - starlink-ast
        - wcslib
      run:
        # jq is special - it is needed for the pin-it utility in this package
        - jq
        ###################################################
        # build-like dependencies
        # As part of our scons build process, we do run tests, so
        # these really are required to perform a build.
        # Note that "testing" in conda-forge should be limited to testing
        # successful packaging, and not testing code.
        - ${{ compiler('c') }}
        - ${{ compiler('cxx') }}
        - ${{ compiler('fortran') }}
        # The above are needed to get the official conda-forge versions.
        # The below is needed to get convenience symlinks for users to invoke.
        - compilers
        - cmake
        # Coverage 6.3 is breaking with NFS and multi-process testing.
        - coverage >=3.6,!=6.3
        - coveralls
        - doxygen <1.9.6
        - flake8 =4.0
        - make
        - nose
        - pep8-naming
        - pip ==24
        - psutil
        - pytest <8.2
        - pytest-cov <6
        - pytest-doctestplus
        - pytest-flake8 <1.2
        - pytest-openfiles
        - pytest-runner
        - pytest-session2file
        - pytest-subtests ==0.12.1
        - pytest-xdist ==3.5
        - scons
        - setuptools <70

        ###################################################
        # host-like and run-like
        # These are mostly run-like, but for the same reasons as
        # above, we need most of these at build time, so they are mostly
        # host-like
        - apr ${{ apr }}.*
        - boost ${{ boost }}.*
        - cffi ${{ cffi }}.*
        - cfitsio ${{ cfitsio }}.*
        - cython ${{ cython }}.*
        - eigen ${{ eigen }}.*
        - eups
        - firefly-client
        - galsim
        - gsl ${{ gsl }}.*
        - libaprutil ${{ libaprutil }}.*
        # there is some issue with pex_exceptions with clang 11 and libcxx 12
        # until it is tracked down, it makes sense to keep these at the same
        # major version
        - if: osx
          then: libcxx ${{ cxx_compiler_version }}.*
        - llvmlite
        - log4cxx ${{ log4cxx }}.*
        - lsst-documenteer-pipelines
        - lsst-documenteer-technote
        - minuit2 ${{ minuit2 }}.*
        - mpich ${{ mpich }}.*
        - ndarray ${{ ndarray }}.*
        - numpy ${{ numpy }}.*
        - numba
        - starlink-ast ${{ starlink_ast }}.*
        - wcslib ${{ wcslib }}.*
        - xpa ${{ xpa }}.*

        ###################################################
        # run-like
        - alembic
        - astropy
        - astroquery <0.4.8
        - autograd
        - backoff
        - boto3
        - bottleneck
        # conda is required for runtime inspection of installed software
        - conda
        - configparser
        - click !=8.1.0,!=8.1.1,<8.2
        - coloredlogs
        - deprecated
        - dustmaps
        - emcee
        - esutil <=0.6.10
        - fitsio <1.3
        - fastavro
        - future
        - git
        - git-lfs
        - h5py
        - healpy
        - healsparse
        - idds-client >=0.11.0
        - idds-doma >=0.11.0
        # inflection may go away in the future; see DM-32591
        - inflection
        - iminuit >=2
        - jaraco.context <4.4
        - jaraco.functools <4.1
        - lmfit <1.0.3
        - urllib3 <2
        - lsstdesc.coord
        - matplotlib-base !=3.6.0,<3.7.0
        - moto >=3,<5
        - mpi4py
        - networkx <3
        - numexpr =2
        - ${{ pin_compatible('numpy') }}
        - pandas <2
        - pgcli
        # Remove < after Spectractor fix: see DM-35580
        - photutils >=0.7,<1.5
        - piff ==1.3.3
        - if: linux
          then: prmon
        - psycopg2 =2
        - pyarrow <13
        - pybind11 <2.10
        - pydantic <2
        - pyld
        - pysynphot
        - pytables
        - python
        - pyyaml
        - requests
        - schwimmbad
        - scikit-image !=0.18,<0.20
        - scikit-learn
        - scipy <1.9
        - seaborn
        - skyproj
        - spherematch <0.10
        - sqlalchemy <2
        - sqlite
        - stomp.py >=8.0.1
        - threadpoolctl
        - tqdm
        - treecorr =4
        - ws4py

    tests:
      - script:
          # grep pin-it output for python dependency
          - pin-it rubin-env-nosysroot | grep "python="
          # ensure binary compatibility; bump major version if not
          - if: linux
            then: '[ $(echo __GXX_ABI_VERSION | ${CXX} -E - | tail -1) == ${{ linux_gxx_abi_version }} ]'
          - if: osx
            then: '[ $(echo __GXX_ABI_VERSION | ${CXX} -E - | tail -1) == ${{ osx_gxx_abi_version }} ]'

  - package:
      name: rubin-env
    requirements:
      host:
        - python
      run:
        - ${{ pin_subpackage("rubin-env-nosysroot", exact=True) }}
        - if: linux
          then: sysroot_linux-64 =2.17
        - python
    tests:
      - script:
          # grep pin-it output for python dependency
          - pin-it rubin-env | grep "python="
          # ensure binary compatibility; bump major version if not
          - if: linux
            then: '[ $(echo __GXX_ABI_VERSION | ${CXX} -E - | tail -1) == ${{ linux_gxx_abi_version }} ]'
          - if: osx
            then: '[ $(echo __GXX_ABI_VERSION | ${CXX} -E - | tail -1) == ${{ osx_gxx_abi_version }} ]'

  - package:
      name: rubin-env-rsp
    requirements:
      host:
        - python
      run:
        - ${{ pin_subpackage("rubin-env", exact=True) }}
        # All are from sciplat-lab unless otherwise stated
        - astroplan # sims
        - astroquery
        - if: not aarch64
          then: astrowidgets
        - awkward
        - awkward-numba
        - black
        - bokeh
        - bqplot
        - if: not aarch64
          then: ciso8601
        - cloudpickle
        - cookiecutter
        - dash
        - dask
        - dask-kubernetes
        - dask_labextension
        - datashader
        - distributed
        - fastparquet
        - ffmpeg # RFC-846
        - freetype-py
        - gcsfs
        - geoviews
        - ginga
        - graphviz
        - holoviews
        - hvplot
        - imagemagick # RFC-846
        - intake
        - intake-parquet
        - ipyevents
        - ipykernel
        - ipympl
        - ipyvolume
        - ipywidgets
        - isort
        - jedi
        - jupyter
        - if: not aarch64
          then: jupyter-dash
        - jupyter-packaging
        - jupyter-server-proxy
        - jupyter_bokeh
        - jupyterhub
        - jupyterlab >=3,<4
        - jupyterlab_execute_time
        - jupyterlab_iframe
        - jupyterlab_widgets
        - mamba
        - mypy
        - mysqlclient
        - nbconvert-webpdf
        - nbdime
        - nbval
        - nodejs >=16
        - numba
        - panel # shared
        - papermill
        - paramnb
        - partd
        - pep8 # shared
        - plotly
        - pre-commit
        - pyflakes # shared
        - pypandoc
        - pyshp
        - python-snappy
        - python-socketio
        - pythreejs
        - pyviz_comms
        - pyvo
        - sidecar
        - snappy
        - terminado
        - toolz
        - wget
        - xarray
        - yarn
    tests:
      - script:
          # grep pin-it output for yarn dependency
          - pin-it rubin-env-rsp | grep "yarn="

  - package:
      name: rubin-env-extras
    requirements:
      host:
        - python
      run:
        - ${{ pin_subpackage("rubin-env", exact=True) }}
        # All are from sciplat-lab unless otherwise stated
        - astroplan # sims
        - astroquery
        - if: not aarch64
          then: astrowidgets
        - awkward
        - awkward-numba
        - black
        - bokeh
        - bqplot
        - if: not aarch64
          then: ciso8601
        - cloudpickle
        - colorcet # sims
        - cookiecutter
        - cycler # sims
        - dash
        - dask
        - dask-jobqueue # shared
        - dask-kubernetes
        - dask_labextension
        - datashader
        - distributed
        - ephem # sims
        - fastparquet
        - ffmpeg # RFC-846
        - freetype-py
        - gcsfs
        - george # sims
        - geoviews
        - ginga
        - graphviz
        - holoviews
        - hvplot
        - imagemagick # RFC-846
        - intake
        - intake-parquet
        - ipdb # shared
        - ipyevents
        - ipykernel
        - ipympl
        - ipyparallel # sims
        - ipyvolume
        - ipywidgets
        - isort
        - jedi
        - jupyter
        - if: not aarch64
          then: jupyter-dash
        - jupyter-packaging
        - jupyter-server-proxy
        - jupyter_bokeh
        - jupyterhub
        - jupyterlab >=3,<4
        - jupyterlab_execute_time
        - jupyterlab_iframe
        - jupyterlab_widgets
        - mypy
        - mysqlclient
        - nbconvert-webpdf
        - nbdime
        - nbval
        - nodejs >=16
        - numba
        - if: not aarch64
          then:
            - openorb # sims
            - openorb-data-de405 # sims
            - palpy # sims
        - panel # shared
        - papermill
        - paramnb
        - partd
        - pep8 # shared
        - plotly
        - pre-commit
        - pyct # shared
        - pyflakes # shared
        - pypandoc
        - pyshp
        - python-snappy
        - python-socketio
        - pythreejs
        - pyviz_comms
        - pyvo
        - sidecar
        - snappy
        - terminado
        - toolz
        - xarray
        - yarn
    tests:
      - script:
          # grep pin-it output for yarn dependency
          - pin-it rubin-env-extras | grep "yarn="
          # ensure binary compatibility; bump major version if not
          - if: linux
            then: '[ $(echo __GXX_ABI_VERSION | ${CXX} -E - | tail -1) == ${{ linux_gxx_abi_version }} ]'
          - if: osx
            then: '[ $(echo __GXX_ABI_VERSION | ${CXX} -E - | tail -1) == ${{ osx_gxx_abi_version }} ]'

about:
  homepage: https://github.com/conda-forge/rubinenv-feedstock
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: Metapackage to install the Rubin Observatory's common software environment.

  description: |
    This metapackage exists to define the Rubin Observatory common software
    environment, including version specifications where needed, while allowing
    users flexibility when installing additional packages into the same environment.

extra:
  recipe-maintainers:
    - brianv0
    - timj
    - ktlim
    - beckermr
    - erykoff
