conda_forge_output_validation: true
build_platform:
  osx_arm64: osx_64
test: native_and_emulated
os_version:
  linux_64: cos7
github:
  branch_name: main
  tooling_branch_name: main
azure:
  store_build_artifacts: true
conda_build:
  pkg_format: '2'
