conda_forge_output_validation: true
build_platform:
  osx_arm64: osx_64
test_on_native_only: true
os_version:
  linux_64: cos7
github:
  branch_name: main
  tooling_branch_name: main
azure:
  store_build_artifacts: true
